#!/usr/bin/env bash

# ######################################################
# AUTHOR: IAROM MADDEN
#
# file preview via tabbed xembed with persistent preview file state.
# files are sent to previewer via interface/server setup
#
# dep: tabbed mpv neovim zathura nuke
# tabbed configured w relative tabs and new pos = 1
# ########################################################

# todo: remove all unecessary code to persistent preview frames..
#   - a major fraction of this file is unrequired now after simplifying certain problems.
# todo: implement a 4th tab: with nuke for alternative files that dont fit into those 3 cats

# init config

pcache="$HOME/.cache/uview"
t_lim="0.1"
nuke="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/plugins/nuke"
term="st -c preview -w"
pager=${PAGER:-"nvim -R"}
#t_lim_xdot="0.5"
#t1="100000"

# init universals
fifox="$1"
f1="$nnn"

{ [ -z "$fifox" ] && [ -f "$NNN_FIFO" ]; } || fifox="$NNN_FIFO"

mkdir -p "$pcache"
log_x="$pcache/uview.log"
log_y="$pcache/uviewy.log"
cache_tt_switch="$pcache/cache.tt.switch"
cache_f_curr="$pcache/cache.f_curr"
[ -n "$MPVX" ] && mpvx="$MPVX" || mpvx="mpv"

#tab_mpv="1" # mpv tab
#tab_nvi="2" # nvim tab
#tab_zat="3" # zathura tab
tab_mpv="1" # mpv tab
tab_nvi="2" # nvim tab
tab_zat="3" # zathura tab

#mime_last="inode/directory" # mime init
#mime_last=""
mime_last="application/pdf" # first visible win is zath
mime_curr=""
f_curr="$f1"

xid=""
pid_view=""
pid_tabd=""

soc_mpv=""
soc_nvim=""
soc_zath=""
#f_last=""


# print ########################################

_prnt()             { printf "%s \n" "$@"; }

_prnt_mime()        { file -bL --mime-type "${1}"; }

_prnt_swit()        { cat "$cache_tt_switch"; }
_prnt_f_cache()     { cat "$cache_f_curr"; }

_prnt_pid_nvim()    { pgrep -f "nvim --listen ${soc_nvim}"; } #?
_prnt_pid_mpv()     { pgrep -f "mpv .*$soc_mpv"; } #?

_debugx()           { _prnt "$1" >> "$log_x" ; }
_set_debug()        { _prnt "uview begin:" > "$log_x" ; }


# set #########################################

_set_cache_f_curr() { _prnt "$f_curr" > "$cache_f_curr"; }
_set_mime_curr()    { mime_curr=$(_prnt_mime "${f_curr}"); }
_set_mime_last()    { mime_last="${mime_curr}"; }

_set_pid_mpv()      { pid_mpv="$(_prnt_pid_mpv)"; }
_set_pid_nvim()     { pid_nvim="$(_prnt_pid_mpv)[1]"; } # why [1]?

printf "y" > "$cache_tt_switch" # add this into a 'init' function


# window/viewers/jobs ########################################

_get_win_id()       { xdotool search --pid "$1" | head -1; } # $1 is $pid

_set_viewer_pid ()  { pid_view="$(jobs -p %%)"; }
_set_fm_win()       { fm_win="$(xdotool getactivewindow)" ; }

_set_winid_mpv()    { winid_mpv="$(_get_win_id "$pid_mpv")"; }
_set_winid_nvim()   { winid_nvim="$(_get_win_id "$pid_nvim")"; }
_set_winid_zath()   { winid_nvim="$(_get_win_id "$pid_zath")"; } #TODO

# winid's are not required now?


# foc

_win_foc_main()     { xdotool windowactivate "$fm_win"; }
_win_foc_mainx()     { sleep 0.8s; xdotool windowactivate "$fm_win"; }
_win_foc_xid()      { xdotool windowactivate "$xid"; }
_win_foc_tabx()     { xdotool key --window "$xid" "Ctrl+$1";  _win_foc_main; }

_win_foc_mpv()      { _win_foc_tabx $tab_mpv; }
_win_foc_nvim()     { _win_foc_tabx $tab_nvi; }
_win_foc_zath()     { _win_foc_tabx $tab_zat; } #TODO

#_win_foc_tabx()     { _win_foc_xid; xdotool key "Ctrl+$1"; } # _win_foc_main; }

#_win_foc_tabx()     { xdotool key --window "$xid" "Ctrl+$1"; } # _win_foc_main; }

#_win_foc_brute()    { _window_foc_brutex; } # unused?

# behave

_win_foc() {
  xid_active="$(xdotool getactivewindow)"
  if [ $((xid_active == xid)) -ne 0 ] ; then
    xdotool windowactivate "$fm_win"
    #xdotool windowactivate --sync "${wid_x}" \
    #else
      #timeout "$t_lim_xdot" xdotool behave "$xid" focus windowactivate "$fm_win" &
  fi; }


# tests

_mime_test_media()  { _prnt "$1" | grep -e "video" -e "image" -e "audio" ; }
_mime_test_vim()    { _prnt "$1" | grep -e "text" -e "inode/directory" ; }
_mime_test_doc()    { _prnt "$1" | grep -e "application/pdf" ; } #todo: epubs..

_test_fifo()        { [ ! -r "$fifox" ] && { echo "\$fifox read fail ('$fifox')"; exit 1; }; }

# wait

_wait() { # creating a while loop instead of sleep x #tod
  c=1
  while -z "$1" && $c lt $2 ; do
    sleep 0.1
    $3
  done ;}


# mime/progs ###################################################

# term

_set_term() {
  if which $term >/dev/null 2>&1 ; then
    term=$term
  elif which st >/dev/null 2>&1 ; then
    term="st -c preview -w"
  elif which urxvt >/dev/null 2>&1 ; then
    term="urxvt -embed"
  elif which xterm >/dev/null 2>&1 ; then
    term="xterm -into"
  else
    _prnt "no xembed term found" >&2
  fi ;}

# todo: incase nuke is not installed, revert to 'less' or 'pager' as defined in config section
#if [ -x "$nuke" ] ; then all() { _term_nuke; }
#  else # shellcheck disable=SC2086
#    all() { $term "$xid" -e sh -c "echo '$f_curr' | $pager -" & }
#  fi 
#txtp()  { $term "$xid" -e $pager "$f_curr" & }

_term_nuke ()  { $term "$xid" -e "$nuke" "$f_curr" & }


# mpv #####################################

_mpvxx() { $mpvx --input-ipc-server="${soc_mpv}" --wid="$xid" --no-focus-on-open --force-window=immediate --idle "${f_curr}" & }
#_mpvxx() { $mpvx --input-ipc-server="${soc_mpv}" --wid="$xid" --no-focus-on-open --force-window=immediate --idle & }

_mpv_set() {
  c=1
  while [[ -z "$pid_mpv" && "$c" -lt 10 ]]; do
    c=$((c + 1))
    _set_pid_mpv
    sleep 0.1
  done ;}

_mpvx() { _mpvxx; 
  #_mpv_set
}

_mpv_add() { printf '%s\n' "{ \"command\": [\"loadfile\", \"$f_curr\", \"replace\" ] }" | socat - "${soc_mpv}" &> /dev/null; }

_mpv() { 
  #[ -n "$pid_mpv" ] || _mpvx
  #sleep 1
  _mpv_add ;}

#_mpv_start() { [ -n "$pid_mpv" ] || _mpvy ; }
#[ -eq "$(_prnt_swit)" = "n" ] && return


# nvim #######################################

_nvimxx() { $term "$xid" -e nvim --listen "${soc_nvim}" -c 'set shortmess+=I | hi CursorLine guibg=black guifg=black' & }

_nvim_set() {
  c=1
  while [[ -z "$pid_nvim" && "$c" -lt 10 ]]; do
    c=$((c + 1))
    _set_pid_nvim
    sleep 0.1
  done ;}

_nvimx() {
  _nvimxx ;}
  #_nvim_set ;}
#[ -z "$pid_nvim" ] && $term "$xid" ;}

_nvim_send() { 
  case $mime_curr in
    text/*)           ncmd=":view ${f_curr}<CR>" ;;
    inode/directory)  ncmd=":view ${f_curr}/<CR>" ;;
  esac
  nvim --server "${soc_nvim}" --remote-send "$ncmd" & }

_nvim() {
  pid_nvim="$(_prnt_pid_nvim)"
  { [ -n "${pid_nvim}" ] && _nvim_send; } \
    || { _nvimx; _nvim_send; }; }


# zath #########################################

_prnt_soc_zath() {
  dbus-send \
    --session \
    --dest=org.freedesktop.DBus \
    --type=method_call          \
    --print-reply               \
    /org/freedesktop/DBus       \
    org.freedesktop.DBus.ListNames | sed -nr '/^.*string "(.*zathura.*)"/{s//\1/p;q;}' ;}

_set_soc_zath () { sleep 1; soc_zath="$(_prnt_soc_zath)" ; }

_zath_send() { # open file
  dbus-send \
    --session  \
    --dest="$soc_zath"  \
    --type=method_call \
    --print-reply      \
    /org/pwmt/zathura  \
    org.pwmt.zathura.OpenDocument \
    string:"${f_curr}" \
    string:'' \
    int32:1 &2>> /dev/null ; }
    #int32:1 2>&1 >> $log_y ; }
    #string:\'"${f_curr}"\' \
    #TODO: issues with some filenames

_zath_pid() {
    _debugx "gdbus:"
    gdbus introspect 
      --session \
      --dest "$soc_zath" \
      --object-path / \
      --only-properties -q >> $log_x
    #grep -oP 'ProcessID=\K\d+'  # Extract ProcessID value using Perl-compatible regular expression
}

_zath_kill() { [ -n "$soc_zath" ] && kill -9 "$(echo "$soc_zath" | sed -n 's/.*PID-\([0-9]\+\).*/\1/p')"; }

_zathx() { zathura -e "$xid" "$f_curr" & sleep 0.5s; _set_soc_id; }

_zath() { 
  [ -n "$(_prnt_soc_zath)" ] && { _zath_send & return; }
  _zathx ;}


# mime handling #############################

_mime_handlers() {
  if which mpv >/dev/null 2>&1 ; then
    media() { _mpv; } else
    media() { _term_nuke; } fi
  if which zathura >/dev/null 2>&1 ; then
    doc() { _zath; }; else
    doc() { _term_nuke; }; fi
  if which nvim >/dev/null 2>&1 ; then
    txtp() { _nvim; }; inodev() { _nvim; }; else
    txtp() { _term_nuke; }; fi
  #if which nvim >/dev/null 2>&1 ; then
  #  alias txtp=_nvim; alias inodev=_nvim; else
  #  alias txtp=_term_nuke; fi
}

_mime_switch() { # mime switches
  [ n = $(_prnt_swit) ] && return

  case "$mime_curr" in
    video/*) media ;;
    audio/*) media ;;
    image/*) media ;;
    application/pdf) doc ;;
    inode/directory) inodev ;;
    text/*) txtp ;;
    #*) all ;;
  esac ;}


# tabbed ########################################


_p_tabbed_start () { # start tabbed
    fifoy="$(mktemp -u)"
    mkfifo "$fifoy"
    tabbed -n preview > "$fifoy" &

    jobs
    pid_tabd="$(jobs -p %%)"
    soc_mpv="/tmp/nnn.${pid_tabd}.mpv"
    soc_nvim="/tmp/nnn.${pid_tabd}.nvim"

    [ -z "$pid_tabd" ] && { echo "Can't start tabbed"; exit 1; }
    read -r xid < "$fifoy" && rm "$fifoy"

    # note: currently, mpv starts quickest, then nvim, then zath. Thus, its a safe bet to initiate them in a partially reversed order with a slight delay after mpv

    _mpvx & sleep 1.9
    _nvimx & sleep 1
    _zathx #change to _zath?
    _set_soc_zath

    #_mpv_xa & sleep 1
    #_zathxa & sleep 1
    #_nvim_start & sleep 1
    #_win_zath_id
    #_mpv_xa & sleep 0.2
    #_nvim_start & sleep 0.5
    #_zathxa & sleep 0.2
    # required anymore?
    #i3-msg 'no_focus [id="$xid"]' # i3 props
    #i3-msg 'for_window [id="$xid"] border 2px'
    #i3-msg 'for_window [instance="preview"] border 2px' ;}
  }

# focus switches #########################################

_mime_test_last() {
  is_last_media=$(_mime_test_media "$mime_last")
  is_last_vim=$(_mime_test_vim "$mime_last")
  is_last_doc=$(_mime_test_doc "$mime_last") ;}

_mime_test_curr() {
  is_curr_media=$(_mime_test_media "$mime_curr")
  is_curr_vim=$(_mime_test_vim "$mime_curr")
  is_curr_doc=$(_mime_test_doc "$mime_curr");}

_foc_viewer_x() { # sol to grab foc of background tabs? #TODO: work in progress
  _mime_test_curr
  _mime_test_last
  [ $mime_curr = $mime_last ] && return
  [ -n "$is_curr_media"  ] && _win_foc_mpv && return
  [ -n "$is_curr_vim"  ] && _win_foc_nvim && return
  [ -n "$is_curr_doc"  ] && _win_foc_zath && return ;}

_tt_sw()  { _prnt "$1" > "$cache_tt_switch"; }

_timer() {
  f_start="${f_curr}"
  _tt_sw "n"
  sleep "$t_lim"
  f_upd="$(_prnt_f_cache)"
  [ $f_start = $f_upd ] && _tt_sw "y" && return ;}
 

# viewing - kill #######################################

# archive these functions

#_kill_viewer_pid() { if [ -n "$pid_view" ] && jobs -p | grep "$pid_view"; then kill "$pid_view"; fi; }

#_kill_mpv() { pid_mpv="$(_prnt_pid_mpv)"; [ -n "$pid_mpv" ] && kill "$pid_mpv"; }

#_kill_nvim() { [ -n "$pid_nvim" ] && for i in $pid_nvim; do kill "$i"; done; }

_kill_viewer() { # viewer
  # if last was vid/txt/node: { curm = lastm -> return || otherwise kill }
  _mime_test_curr
  _mime_test_last
  [ -n "$is_last_media"  ] && return
  [ -n "$is_last_vim"  ] && return
  [ -n "$is_last_doc"  ] && return
  #[ -n "$is_last_media"  ] && [ -n "$is_curr_media" ] && return
  #[ -n "$is_last_vim"  ] && [ -n "$is_curr_vim" ] && return
  #[ -n "$is_last_doc"  ] && [ -n "$is_curr_doc" ] && return
  #_kill_nvim 
  #_kill_mpv
  _kill_viewer_pid ; }

# Cleanup #####################################################

_kill_tabbed() { kill "$pid_tabd"; }

_kill_fifos()  { rm -f "$soc_mpv" "$soc_nvim"; }

_kill_all()    { _kill_tabbed; _kill_fifos; _zath_kill; disown; exit 0 ; }


# body - init ########################################################

_init() { # init sigs
  _test_fifo
  _set_term
  #unset -v fifox #?
  exec >/dev/null 2>&1  # mute from now
  trap _kill_all SIGINT

  # init tabbed
  _set_fm_win
  _p_tabbed_start
  _win_foc_mainx &

  # init handles
  _mime_handlers
  _loopx 
  }


# body - loop #####################################################

_loop_init() { # init new file arg
  [ ! -e "$f_curr" ] && continue
  _set_cache_f_curr
  _set_mime_curr
  jobs && if ! jobs | grep tabbed ; then break; fi ; }

_loop_view() {
  _foc_viewer_x
  _mime_switch 
  _timer & }

_loop_close() {
  _set_mime_last
  _win_foc ;}

_loopx() {
  _loop_init
  _loop_view
  _loop_close ;}

_loop() { 
  while read -r f_curr ; do 
    _loopx ; 
  done < "$fifox"; }


# main #######################################################

_main () {
  _init
  _loop
  _kill_all ;}


_main &

